web:
  build: .
  volumes:
  - /home/core/projects/zendcon-docker:/site
  ports:
  - 8080:80
  links:
  - mysql
  - memcached

memcached:
  image: memcached

mysql:
  image: mysql:5.6.24
  command: mysqld --user=root --verbose --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: site
    MYSQL_USER: site
    MYSQL_PASSWORD: site